### ISSUE TITLE
User Information

### ISSUE THREAD

**Issue by Maharlikoders** [ridwaanhall/hero-statistics-in-MLBB#1]
How about retrieving Username and User's avatar?

**Comment by ridwaanhall** [comment]
for username, i have created URL endpoint by using id and zone id to get username/nickname (my old project). for user's avatar, i didn't get solution for that.

**Comment by Maharlikoders** [comment]
Thanks for the update! Anyway, could you clarify whether the new hero is not being retrieved from the source? I'm encountering an issue where the new hero isn't appearing as expected, and I wanted to confirm if that's related to the source or if it's something else. Any insights would be appreciated.

**Comment by ridwaanhall** [comment]
which new hero do you mean? is it suyou? i will re-check later, because i have other work. i will take the time to check the source of the problem if possible.

**Comment by ridwaanhall** [comment]
the code is up to date now. if you got any problems, you can create pull requests.

**Comment by Maharlikoders** [comment]
Thank you for the update! Will this update include upcoming new heroes?

**Comment by ridwaanhall** [comment]
you're welcome. every release new hero, it will update. so, this update is for hero with name Suyou. next will update for hero with name Lukas.

**Comment by Maharlikoders** [comment]
Just to clarify, the previous version didn’t include the upcoming heroes, right? Will this update now include them?

**Comment by ridwaanhall** [comment]
yes. this update includes Suyou.

**Comment by Maharlikoders** [comment]
Sorry, I mean upcoming heroes like Lucas(127) to be specific and the sea creature girl(128) in the survey? Will this changes be included (upcoming)heroes when they've been release? Thanks again for the fast response.

**Comment by ridwaanhall** [comment]
this changes for Suyou hero. the upcoming hero like lucas and girl hero, it will update again (maintenance for getting a new data). so, every new hero, the list isnt show until i update the data. i hope you know what i mean, but, if you dont know, i will explain again.

**Comment by Maharlikoders** [comment]
Alright I get it now. Thank u

**Comment by Maharlikoders** [comment]
Thanks maybe I'll reopen this again when there's a new hero to inform you

**Comment by ridwaanhall** [comment]
youre welcome, okay
